# Generated by Django 5.0.7 on 2024-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_amazonproduct_session_id_amazonproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonproduct',
            old_name='session_id',
            new_name='sessionId',
        ),
    ]
