# Generated by Django 5.0.7 on 2024-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_alter_amazonproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
