# Generated by Django 5.0.7 on 2024-09-02 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_alter_amazonproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sessionId',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
