# Generated by Django 5.0.7 on 2024-09-05 07:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_sentimentresult_sessionid_sentimentresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipkartproduct',
            name='sessionId',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flipkartproduct',
            name='user',
            field=models.CharField(default=datetime.datetime(2024, 9, 5, 7, 4, 55, 941608, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
