# Generated by Django 5.0.7 on 2024-09-06 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_flipkartproduct_sessionid_flipkartproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstoreproduct',
            name='sessionId',
            field=models.CharField(default=datetime.datetime(2024, 9, 6, 6, 50, 34, 550228, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playstoreproduct',
            name='user',
            field=models.CharField(default=datetime.datetime(2024, 9, 6, 6, 50, 42, 730343, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
